### ISSUE TITLE
No README.md file

### ISSUE THREAD

**Issue by AnthonyTurrigiano** [thinkphase/ng2-boilerplate#1]
There is not README.md file in the repo

**Comment by trippleo** [comment]
Comments

**Comment by AnthonyTurrigiano** [comment]
Alex stop talking and do this :)

**Comment by iamalexcohen** [comment]
Boo Anthony!

**Comment by iamalexcohen** [comment]
added my Alex Cohen ADM folder (idea) includes readme.md.
Adding remaining files in next versions
